### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by turb1te** [nyancodeid/bandwidth-hero-proxy#5]
Hi @nyancodeid , 🙂

How can I use your fork with Heroku? I tried to make a fork of your project and after that to deploy to Heroku but without success. Thanks!

![image](https://user-images.githubusercontent.com/44940748/100621779-c282ea00-3328-11eb-8c4c-bd3bfd460d8b.png)

**Comment by nyancodeid** [comment]
Hi,  @turb1te. This fork need docker-compose run first to make it run rethinkdb. And 'til now i don't know how to configure it on heroku and what should i write on configuration file. 

'cause this repository structure and how it's work is totally different from the original, that's why we need different treatment.

**Comment by LexterS999** [comment]
I try to fork your git and added app.json from original git, but it's still show error

-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.20.0...
       Using default npm version: 6.14.8
       
-----> Installing dependencies
       Installing node modules
       
       > fsevents@1.2.13 install /tmp/build_d242d8f1_/node_modules/fsevents
       > node install.js
       
       
       Skipping 'fsevents' build as platform linux is not supported
       
       > sharp@0.25.4 install /tmp/build_d242d8f1_/node_modules/sharp
       > (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
       
       info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz
       
       > bcrypt@5.0.0 install /tmp/build_d242d8f1_/node_modules/bcrypt
       > node-pre-gyp install --fallback-to-build
       
       [bcrypt] Success: "/tmp/build_d242d8f1_/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote
       
       > nodemon@2.0.4 postinstall /tmp/build_d242d8f1_/node_modules/nodemon
       > node bin/postinstall || exit 0
       
       Love nodemon? You can now support the project via the open collective:
        > https://opencollective.com/nodemon/donate
       
       
       > core-js@3.6.5 postinstall /tmp/build_d242d8f1_/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       added 1009 packages in 16.493s
       
-----> Build
       Running build
       
       > node-project-blueprint@2.1.0 build /tmp/build_d242d8f1_
       > npm run clean && npm run build:source && cp -r ./src/views ./build/views
       
       
       > node-project-blueprint@2.1.0 clean /tmp/build_d242d8f1_
       > rm -rf build && mkdir build
       
       
       > node-project-blueprint@2.1.0 build:source /tmp/build_d242d8f1_
       > babel -d ./build ./src -s
       
       Successfully compiled 13 files with Babel (1102ms).
       
-----> Caching build
       - node_modules
       
-----> Pruning devDependencies
       removed 740 packages and audited 263 packages in 10.05s
       
       10 packages are looking for funding
         run `npm fund` for details
       
       found 3 vulnerabilities (2 low, 1 high)
         run `npm audit fix` to fix them, or `npm audit` for details
       
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
       Done: 36.7M
-----> Launching...
       Released v3
       https://****.herokuapp.com/ deployed to Heroku

I'm trying to paste compiled version on extension, and it gives me that error Invalid compression service address
Given URL does not appear to be running Bandwidth Hero data compression service.

**Comment by nyancodeid** [comment]
> I try to fork your git and added app.json from original git, but it's still show error
> 
> -----> Node.js app detected
> 
> -----> Creating runtime environment
> 
> ```
>    NPM_CONFIG_LOGLEVEL=error
>    NODE_ENV=production
>    NODE_MODULES_CACHE=true
>    NODE_VERBOSE=false
> ```
> 
> -----> Installing binaries
> engines.node (package.json): unspecified
> engines.npm (package.json): unspecified (use default)
> 
> ```
>    Resolving node version 12.x...
>    Downloading and installing node 12.20.0...
>    Using default npm version: 6.14.8
> ```
> 
> -----> Installing dependencies
> Installing node modules
> 
> ```
>    > fsevents@1.2.13 install /tmp/build_d242d8f1_/node_modules/fsevents
>    > node install.js
>    
>    
>    Skipping 'fsevents' build as platform linux is not supported
>    
>    > sharp@0.25.4 install /tmp/build_d242d8f1_/node_modules/sharp
>    > (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
>    
>    info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz
>    
>    > bcrypt@5.0.0 install /tmp/build_d242d8f1_/node_modules/bcrypt
>    > node-pre-gyp install --fallback-to-build
>    
>    [bcrypt] Success: "/tmp/build_d242d8f1_/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote
>    
>    > nodemon@2.0.4 postinstall /tmp/build_d242d8f1_/node_modules/nodemon
>    > node bin/postinstall || exit 0
>    
>    Love nodemon? You can now support the project via the open collective:
>     > https://opencollective.com/nodemon/donate
>    
>    
>    > core-js@3.6.5 postinstall /tmp/build_d242d8f1_/node_modules/core-js
>    > node -e "try{require('./postinstall')}catch(e){}"
>    
>    added 1009 packages in 16.493s
> ```
> 
> -----> Build
> Running build
> 
> ```
>    > node-project-blueprint@2.1.0 build /tmp/build_d242d8f1_
>    > npm run clean && npm run build:source && cp -r ./src/views ./build/views
>    
>    
>    > node-project-blueprint@2.1.0 clean /tmp/build_d242d8f1_
>    > rm -rf build && mkdir build
>    
>    
>    > node-project-blueprint@2.1.0 build:source /tmp/build_d242d8f1_
>    > babel -d ./build ./src -s
>    
>    Successfully compiled 13 files with Babel (1102ms).
> ```
> 
> -----> Caching build
> - node_modules
> 
> -----> Pruning devDependencies
> removed 740 packages and audited 263 packages in 10.05s
> 
> ```
>    10 packages are looking for funding
>      run `npm fund` for details
>    
>    found 3 vulnerabilities (2 low, 1 high)
>      run `npm audit fix` to fix them, or `npm audit` for details
> ```
> 
> -----> Build succeeded!
> -----> Discovering process types
> Procfile declares types -> (none)
> Default types for buildpack -> web
> -----> Compressing...
> Done: 36.7M
> -----> Launching...
> Released v3
> https://****.herokuapp.com/ deployed to Heroku
> 
> I'm trying to paste compiled version on extension, and it gives me that error Invalid compression service address
> Given URL does not appear to be running Bandwidth Hero data compression service.

Unfortunately, this repository not compatible with Heroku yet. cause we need run docker-compose first. I think we can create unauthenticated version so we can use heroku as a server.

**Comment by nyancodeid** [comment]
Now, it's available. Happy deploy to Heroku :)

**Comment by LexterS999** [comment]
Deployed on Heroku and paste generated URL but got this error: Invalid compression service address
Given URL does not appear to be running Bandwidth Hero data compression service.

**Comment by Mark0001234** [comment]
yes

> Deployed on Heroku and paste generated URL but got this error: Invalid compression service address Given URL does not appear to be running Bandwidth Hero data compression service.

yes
